FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.loader.txt .
RUN pip install --no-cache-dir -r requirements.loader.txt

COPY loader.py .

RUN useradd -m appuser
USER appuser

CMD ["python", "loader.py"]
